%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\sofia\Downloads\MotorCD_EquipoAPerturbaciónTeclaE.CSV
%
% Auto-generated by MATLAB on 26-Aug-2021 23:38:33

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tiempo", "CONTROL", "VELOCIDA", "REFERENC"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Tiempo", "CONTROL" , "VELOCIDA", "REFERENC"], "FillValue", 0);

% Import the data
tbl = readtable("C:\Users\sofia\Downloads\MotorCD_EquipoAPerturbaciónTeclaE.CSV", opts);


%% Clear temporary variables
clear opts

%% Convert to output type
Tiempo = tbl.Tiempo;
CONTROL = tbl.CONTROL;
VELOCIDAD = tbl.VELOCIDA;
REF = tbl.REFERENC;

%% Plot
plot(Tiempo, [VELOCIDAD, REF, CONTROL]),
xlabel('Tiempo')
title('Título')
