%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\Grua\Datos\GRUA_EquipoA_UP.CSV
%
% Auto-generated by MATLAB on 28-Oct-2021 16:12:25

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tiempo", "REI1", "V_ANGULA", "V_CARRIT", "ANGULO", "CARRITO", "REFERENC"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\Grua\Datos\GRUA_EquipoA_UP.CSV", opts);

%% Convert to output type
Tiempo = tbl.Tiempo;
REI1 = tbl.REI1;
V_ANGULA = tbl.V_ANGULA;
V_CARRIT = tbl.V_CARRIT;
ANGULO = tbl.ANGULO;
CARRITO = tbl.CARRITO;
REFERENC = tbl.REFERENC;

%% Clear temporary variables
clear opts tbl

%% Gráficas
plot(Tiempo, [ANGULO, CARRITO, REFERENC]),
xlabel('Tiempo')
title('Resultados controlador REI por ubicación de polos')