%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\Heli2DoF\Pruebas\HELI - LQR -GrA.CSV
%
% Auto-generated by MATLAB on 10-Nov-2021 00:25:04

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tiempo", "U_YAW", "U_PITCH", "W_YAW", "W_PITCH", "YAW", "PITCH"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\Heli2DoF\Pruebas\HELI - LQR -GrA.CSV", opts);

%% Convert to output type
Tiempo = tbl.Tiempo;
U_YAW = tbl.U_YAW;
U_PITCH = tbl.U_PITCH;
W_YAW = tbl.W_YAW;
W_PITCH = tbl.W_PITCH;
YAW = tbl.YAW;
PITCH = tbl.PITCH;

%% Clear temporary variables
clear opts tbl