%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\PAMH\Modelo\PAMH_DatosRampa_Gr2LabControl.csv
%
% Auto-generated by MATLAB on 14-Sep-2021 17:00:31

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tiempo", "ANGULO", "ENTRADA", "ESTIMULO", "PERTURBA"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\PAMH\Modelo\PAMH_DatosRampa_Gr2LabControl.csv", opts);

%% Convert to output type
Tiempo = tbl.Tiempo;
ANGULO = tbl.ANGULO;
ENTRADA = tbl.ENTRADA;
ESTIMULO = tbl.ESTIMULO;
PERTURBA = tbl.PERTURBA;

%% Clear temporary variables
clear opts tbl