%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\PAMH\Modelo\PAMH_DatosEscalon_Gr2LabControl.csv
%
% Auto-generated by MATLAB on 14-Sep-2021 16:59:37

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Tiempo", "ESTIMULO", "ANGULO"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\sofia\OneDrive - Estudiantes ITCR\TEC\2021\Segundo Semestre\Lab de Control\Lab-Control\PAMH\Modelo\PAMH_DatosEscalon_Gr2LabControl.csv", opts);

%% Convert to output type
Tiempo = tbl.Tiempo;
ESTIMULO_E = tbl.ESTIMULO;
ANGULO_E = tbl.ANGULO;

%% Clear temporary variables
clear opts tbl