%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Y:\S2 2021\Lab Control Automático\Grua\GRUA_centropos.CSV
%
% Auto-generated by MATLAB on 11-Oct-2021 23:24:17

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Tiempo", "Entrada", "Angulo", "Posicion"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Tiempo", "Entrada", "Angulo", "Posicion"], "FillValue", 0);

% Import the data
tbl = readtable("Y:\S2 2021\Lab Control Automático\Grua\GRUA_centropos.CSV", opts);

%% Convert to output type
Tiempo = tbl.Tiempo;
Entrada = tbl.Entrada;
Angulo = tbl.Angulo;
Posicion = tbl.Posicion;

%% Clear temporary variables
clear opts tblh

deltaT = Tiempo(2)-Tiempo(1);
Grua = iddata([Angulo, Posicion], [Entrada], deltaT);
Grua.inputname = {'Entrada'};
Grua.outputname = {'Angulo';'Posicion'};